<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.*" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.*" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QUEBRIX.Logger.SDK\QUEBRIX.Logger.SDK.csproj" />
    <ProjectReference Include="..\QUEBRIX.Logger.Sink\QUEBRIX.Logger.Sink.csproj" />
    <ProjectReference Include="..\QUEBRIX.Logger.Common\QUEBRIX.Logger.Common.csproj" />
    <ProjectReference Include="..\QUEBRIX.Logger.Contracts\QUEBRIX.Logger.Contracts.csproj" />
  </ItemGroup>

</Project>